import type { Metadata } from 'next'

import { jost } from '@/app/fonts'
import { Providers } from '@/app/providers'
import LayoutUI from '@/components/LayoutUI'
import './globals.css'

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={jost.className}>
      <body>
        <Providers>
          <LayoutUI>{children}</LayoutUI>
        </Providers>
      </body>
    </html>
  )
}
