[package]
workspace = "../.."
name = "contracts"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { version = "1.2.0" }

[dev-dependencies]
scrypto-test = { version = "1.2.0" }

[features]
default = []

[lib]
crate-type = ["cdylib", "lib"]

#[workspace]
# Set the package crate as its own empty workspace, to hide it from any potential ancestor workspace
# Remove this [workspace] section if you intend the package to be part of a Cargo workspace
